// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	GetUser(ctx context.Context, id int32) (User, error)
	ListPartners(ctx context.Context, userID int32) ([]ListPartnersRow, error)
	ListPotentialPartners(ctx context.Context, userID int32) ([]ListPotentialPartnersRow, error)
}

var _ Querier = (*Queries)(nil)
